import Head from 'next/head'
import Link from "next/link"
import Image from 'next/image'
import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import { useEffect } from "react"
import { removeOverflowHidden, addOverflowHidden } from "../../lib/homeOverflowStyles"

export default function BlogHome({ posts }) {
  useEffect(() => {
    removeOverflowHidden()

    return addOverflowHidden
  }, [])

  return (


    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-20 px-10 lg:max-w-5xl lg:mx-auto flex flex-col gap-10">

        <section className='py-5 w-max'>
          <dl >
            <dt className="text-3xl text-gray-300 tracking-widest font-light py-2">
              posts
            </dt>
            <dd className="py-2  font-extrabold text-2xl lg:text-4xl">
              {posts.map((post, index) => (
                <Link  href={`blog/${post.slug}`} key={index}>{post.frontMatter.title}</Link>
              ))}
            </dd>
          </dl>
        </section>
      </div>



    </div>
  )
}


export const getStaticProps = async () => {
  const files = fs.readdirSync(path.join('posts'))

  const posts = files.map(filename => {
    const source = fs.readFileSync(path.join('posts', filename), 'utf-8')
    const { data: frontMatter } = matter(source)

    return {
      frontMatter,
      slug: filename.split('.')[0]
    }
  })

  return {
    props: {
      posts
    }
  }
}